export async function GET() {
  return Response.json({
    medicines: [
      {
        id: 1,
        name: "Paracetamol",
        type: "Painkiller",
        description: "Used for fever and mild pain relief",
        price: 50,
        image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88",
        forensic_flag: false,
      },
      {
        id: 2,
        name: "Morphine",
        type: "Controlled",
        description: "Strong pain relief used in severe cases",
        price: 300,
        image: "https://images.unsplash.com/photo-1588776814546-ec7e4b3e0f6c",
        forensic_flag: true,
      },
      {
        id: 3,
        name: "Ibuprofen",
        type: "Anti-inflammatory",
        description: "Reduces inflammation and pain",
        price: 80,
        image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2",
        forensic_flag: false,
      },
      {
        id: 4,
        name: "Aspirin",
        type: "Painkiller",
        description: "Used for headaches and blood thinning",
        price: 60,
        image: "https://images.unsplash.com/photo-1580281657521-16b5e8c2a6a1",
        forensic_flag: false,
      },
      {
        id: 5,
        name: "Amoxicillin",
        type: "Antibiotic",
        description: "Treats bacterial infections",
        price: 120,
        image: "https://images.unsplash.com/photo-1581594693702-fbdc51b2763b",
        forensic_flag: false,
      },
      {
        id: 6,
        name: "Codeine",
        type: "Controlled",
        description: "Used for pain and cough suppression",
        price: 200,
        image: "https://images.unsplash.com/photo-1588776814546-ec7e4b3e0f6c",
        forensic_flag: true,
      },
      {
        id: 7,
        name: "Cetirizine",
        type: "Antihistamine",
        description: "Relieves allergy symptoms",
        price: 40,
        image: "https://images.unsplash.com/photo-1582719471384-894fbb16e074",
        forensic_flag: false,
      },
      {
        id: 8,
        name: "Metformin",
        type: "Diabetes",
        description: "Controls blood sugar levels",
        price: 150,
        image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2",
        forensic_flag: false,
      },
      {
        id: 9,
        name: "Insulin",
        type: "Hormone",
        description: "Used in diabetes management",
        price: 500,
        image: "https://images.unsplash.com/photo-1582719471384-894fbb16e074",
        forensic_flag: false,
      },
      {
        id: 10,
        name: "Tramadol",
        type: "Controlled",
        description: "Moderate to severe pain relief",
        price: 250,
        image: "https://images.unsplash.com/photo-1588776814546-ec7e4b3e0f6c",
        forensic_flag: true,
      },

      // 11–30 (shorter but complete)
      ...Array.from({ length: 20 }, (_, i) => ({
        id: i + 11,
        name: `Medicine ${i + 11}`,
        type: i % 3 === 0 ? "Antibiotic" : "General",
        description: "Generic medicine for treatment purposes",
        price: 100 + i * 10,
        image: "https://images.unsplash.com/photo-1580281657521-16b5e8c2a6a1",
        forensic_flag: i % 5 === 0, // some restricted
      })),
    ],
  });
}